### ISSUE TITLE
Index out of range: baseTriad[4]

### ISSUE THREAD

**Issue by Blaaznar** [mbitson/mcg#109] opened 2019-09-05 07:14 UTC
Returns no errors but seems to be a bug:

`var baseTriad = tinycolor(hex).tetrad();`

This returns a zero based array 0-3:
```
["#500a28", "#4b500a", "#0a5032", "#0f0a50"]
    0: "#500a28"
    1: "#4b500a"
    2: "#0a5032"
    3: "#0f0a50"
```
`baseTriad[4]` is thus out of range and returns undefined.

**Comment by mbitson** [comment] 2020-04-29 02:59
Hey there @Blaaznar !

Thank you for your report! This has recently been fixed in this PR: https://github.com/mbitson/mcg/pull/105

I've got this deployed now to the tool, here: http://mcg.mbitson.com/

Please let me know if you notice anything else! Thanks again!

**Closed as completed by mbitson** 2020-04-29 02:59 UTC

**Comment by micobarac** [comment] 2023-12-29 10:38
Observing the latest source code, the issue is still present.
This piece of code shouldn't work at all:

```typescript
case 'constantin':
var baseLight = tinycolor('#ffffff');
var baseDark = $scope.multiply(tinycolor(hex).toRgb(), tinycolor(hex).toRgb());
var baseTriad = tinycolor(hex).tetrad();
return [
	getColorObject(tinycolor.mix(baseLight, hex, 12), '50'),
	getColorObject(tinycolor.mix(baseLight, hex, 30), '100'),
	getColorObject(tinycolor.mix(baseLight, hex, 50), '200'),
	getColorObject(tinycolor.mix(baseLight, hex, 70), '300'),
	getColorObject(tinycolor.mix(baseLight, hex, 85), '400'),
	getColorObject(tinycolor.mix(baseLight, hex, 100), '500'),
	getColorObject(tinycolor.mix(baseDark, hex, 87), '600'),
	getColorObject(tinycolor.mix(baseDark, hex, 70), '700'),
	getColorObject(tinycolor.mix(baseDark, hex, 54), '800'),
	getColorObject(tinycolor.mix(baseDark, hex, 25), '900'),
	getColorObject(tinycolor.mix(baseDark, baseTriad[4], 15).saturate(80).lighten(65), 'A100'),
	getColorObject(tinycolor.mix(baseDark, baseTriad[4], 15).saturate(80).lighten(55), 'A200'),
	getColorObject(tinycolor.mix(baseDark, baseTriad[4], 15).saturate(100).lighten(45), 'A400'),
	getColorObject(tinycolor.mix(baseDark, baseTriad[4], 15).saturate(100).lighten(40), 'A700')
];
```

`var baseTriad = tinycolor(hex).tetrad();` // this variable should be renamed to `baseTetrad`.
`baseTriad[4]` is still out of bounds and returns `undefined`.

Still scratching my head how on earth does this work at all???

Btw, generated accent colors don't resemble much the default accent colors generated by  Material algorithm (ie. red, indigo, blue...).

**Comment by jlaine** [comment] 2024-11-14 17:32
The code kind of works because tinycolor treats `undefined` as if you had passed black (#000000), so you end up mixing `baseDark` with black then tinkering with saturation and lightness.
